version: "3.7"

services:
  web:
    build: ""
    command: gunicorn --bind 0.0.0.0:8000 config.wsgi:application --reload
    volumes:
      - .:/code
    ports:
      - "8001:8000"
    restart: unless-stopped
